---
- name: Check for SetUID, SetGID, and Sticky Bit on Files and Directories
  hosts: all
  become: yes

  tasks:
    - name: Find SetUID, SetGID, and Sticky Bit Files and Directories
      shell: find / \( -type f -o -type d \) \( -perm -4000 -o -perm -2000 -o -perm -1000 \) -exec ls -ld {} \;
      register: setuid_gid_sticky_files

    - name: Display SetUID, SetGID, and Sticky Bit Files and Directories
      debug:
        var: setuid_gid_sticky_files.stdout_lines
